language: python
python:
- '3.6'
- 3.6-dev
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest
deploy:
  provider: pypi
  user: pmichel31415
  password:
    secure: bvdqnrryNgV8X0mifhLDq2gdYvPgODDaRmyCmwB5HxJ5tLPHFqS2FM6et4mYGvEjssR3BzXVLkYc2LO1FJNG8tLUHnsWWPgiCFGic5FsAomxJmctqbfJHWkBJmPLhY84mm9U8mJPAPrr6/k34ywk5APB2uS3ALRdad7rzSN47c19+k7qqmvuYCukvOgyJ/dM1Z6/+SuIO910e6wfIesOiCKnEzu9gsx9TO/l2EjydJ3IzB9WnKUxSBkkuZI8h0yv2xYkH/puQM1PzcvBmFvzfhLFQlhRnoB3v0vG5oHfvVfGh9DiRN1FMZwijtupwkV1cTTH28xh2Vx7dSaLNC6MyNgXeqY5FWfostM0HKYy9PooIHfGAljOtrFcd1kEmFdSSSBEBzX3pwMU/b47bl+tTihDt1CMSscPDzrnro79HDkJfJHhFrREtqp6wxVsEzzJGOwTqZvk//5QWzyHC4+hkM1YiPS4FiZUIZnesub2+ISqLYfKPj/l04nROJeFtZcQEiB/eeA5BGeR8OBjbFWKfvdURVltr4bvx8t0u8HJ3/2SrmBzhsUoEKEycs0dV41xSzwZzUDlVKR+4Qi8On3uwseNikrcChfy3trVv0EgDMt0VqFsA/17dq8wMsbMcZljGUu7APkc8SeQcJpe0wvxCMq0RpTwj1pWcrSKv7K6KGo=
