language: python
python:
- '3.6'
- 3.6-dev
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest
deploy:
  provider: pypi
  user: pmichel31415
  password:
    secure: Bun20fcD4IOt4Q4W82XUgfes5vgyN/GiFSQySqi+1L8kWXs+PEg4qzb8AymBL81W5Z0gwUJSxWNl1P+3qiBJ8QHpReYTeNR7GRFlGhE1gjK7Y+USOZr1ELSy5tJjTdraP/J1I9zvTA/px+OlGNLasLVLn8vOOreUplp9Jj5h5RjvdZ29R1xZ3cFzRUZiO4C7pZkqp4+3Zf8v8jSRHpnF9H1huL46UU5OZTiOShel7kh9GX9S1uhsFWQNEa7ZUjAsjAieFhUrZxsDVGfZAHOh5sHKNgVguTPSVHHFMCf3U7SFcfjZS/6pF0Htn5oBqjxUYVY5g3E9ccyqJRtDVwzz10CiyCxmAGgbObTiQPGVEBiCu9kLkgULtthRccn+J0R+II3+gYDHuzOWX7MhSBlYsLyVcP6Vcjp1BPe5XEjzdYWn6Yztg7i3azuunji5ViYGJ7K6sB3yJ26ACdLKoWsbMPmSsR9QWwu45FaoyTW5UgDvxG8r00RjugxEW8pWpsl1Vbrb/snEgSfrIErjm9pBr1l66bNCcQ5xzXIR6ECtiCgozYZeA3zU5rCcDuW7hIQBTQXQjTiSqei/xdW3xmRbUTyyFZueE1tdZ36eneT2dmWSIdIwxuzE/iNZaEeVK1NKI71tnuvmbm6MblUzdl/DwpIvEp9fjaBELiobvjSXenA=
